# Generated by Django 5.1.4 on 2025-02-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpm', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
